### ISSUE TITLE
启动服务后，无反应

### ISSUE THREAD

**Issue by NotGeekAtAll** [yafoo/melog#5]
执行`node server.js`后，浏览器访问`http://127.0.0.1:3003`，显示`Internal Server Error`
[https://files.catbox.moe/j4ipep.png](url)

**Comment by yafoo** [comment]
修改/config/app.js文件，打开调试模式
`app_debug: true,`
然后看页面报什么错？顺便看看控制台输出什么信息

**Comment by yafoo** [comment]
> 执行`node server.js`后，浏览器访问`http://127.0.0.1:3003`，显示`Internal Server Error`
> [https://files.catbox.moe/j4ipep.png](url)

修改/config/app.js文件，打开调试模式
`app_debug: true,`
然后看页面报什么错？顺便看看控制台输出什么信息

**Comment by NotGeekAtAll** [comment]
打开调试模式后，数据库连接报错，通过这个方法弄好了[https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server](url)

**Comment by yafoo** [comment]
好的，看起来是数据库版本得问题，后面我看看怎么改善

**Comment by NotGeekAtAll** [comment]
上传文件有点问题，`jj.js`的`fs.js`，`mkdirs`方法的`pathtmp`需要加一个`'/'`，不然目录是读不到的
[图片](https://files.catbox.moe/jdoe79.png)

**Comment by yafoo** [comment]
感谢提供bug，递归生成目录的函数重写了，你更新后再试试！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月18日(星期六) 下午3:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yafoo/melog] 启动服务后，无反应 (#5)





 
上传文件有点问题，jj.js的fs.js，mkdirs方法的pathtmp需要加一个'/'，不然目录是读不到的
 图片
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
